# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: artigno
service: laravel
stages:
  default:
    resolvers:
      awsAccount1:
        type: aws
        region: eu-central-1
        euSsm:
          type: ssm
          region: eu-central-1
provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: eu-central-1
    runtime: provided.al2
    # Environment variables
    environment:
      APP_NAME: Lottery
      APP_ENV: production
      APP_KEY: base64:3PquE7XiJrfTnCpT4elvQMLhc3YopboAGXkIH/A7j1Y=
      APP_DEBUG: true
      APP_TIMEZONE: UTC
      APP_URL: https://dxsyts32b5.execute-api.eu-central-1.amazonaws.com
      APP_LOCALE: pl
      APP_FALLBACK_LOCALE: pl
      APP_FAKER_LOCALE: pl_PL
      APP_MAINTENANCE_DRIVER: file
      APP_MAINTENANCE_STORE: database
      BCRYPT_ROUNDS: 12
      LOG_CHANNEL: stack
      LOG_STACK: single
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: frog01.mikr.us
      DB_PORT: 31166
      DB_DATABASE: losowanie
      DB_USERNAME: ${awsAccount1:euSsm:/lottery/prod/DB_USERNAME}
      DB_PASSWORD: ${awsAccount1:euSsm:/lottery/prod/DB_PASSWORD}
      SESSION_DRIVER: database
      SESSION_LIFETIME: 120
      SESSION_ENCRYPT: false
      SESSION_PATH: /
      SESSION_DOMAIN: null
      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: database
      CACHE_STORE: database
      CACHE_PREFIX:
      MEMCACHED_HOST: 127.0.0.1
      REDIS_CLIENT: phpredis
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MAIL_MAILER: log
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 2525
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: "${APP_NAME}"
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET:
      AWS_USE_PATH_STYLE_ENDPOINT: false
      VITE_APP_NAME: "${APP_NAME}"
      SMS_API_TOKEN: ${awsAccount1:euSsm:/lottery/prod/SMS_API_TOKEN}
plugins:
  # We need to include the Bref plugin
  - ./vendor/bref/bref

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'

functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-82-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-82-console
        timeout: 720 # in seconds
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'
